substitutions:
  devicename: "esp-talk-d6-br"
  board: "lolin_s2_mini"
  reboot_timeout: 2min
  ota_password: !secret talk_d6_ota
  api_key: !secret talk_d6_key
  lrclk_pin: "GPIO39"
  bclk_pin: "GPIO35"
  dout_pin: "GPIO18"

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  speaker: !include common/speaker.yaml
  wifi: !include common/wifi-public.yaml
  portal: !include common/portal.yaml

