substitutions:
  devicename: "esp-plantcam"

  # ESP32
  board: esp32cam

  # Core
  ota_password: !secret plantcam_ota
  api_key: !secret plantcam_key

  # Wifi
  reboot_timeout: 5min

  # Camera
  resolution: 1280x1024
  jpeg_quality: "12"
  agc_gain_ceiling: 64x # 2x # 32x # 64x # 128x
  aec2: "true"
  ae_level: "1"
  brightness: "1"
  saturation: "1"

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  camera: !include common/espcam.yaml
  stream: !include common/espcam-web.yaml
  snap: !include
    file: common/espcam-web.yaml
    vars:
      mode: snapshot
      port: "8081"
  wifi: !include common/wifi-iot.yaml
  portal: !include common/portal.yaml

