substitutions:
  devicename: "esp-sb2"
  reboot_timeout: 5min
  fast_connect: "true"

  # Core
  ota_password: !secret sb2_ota
  api_key: !secret sb2_key

  voltage_divider: "1375"

  # Scheduler
  timezone: "America/New_York"
  schedule_minutes: "/5" # Check every x minutes
  entity_sunrise: "input_number.nursery_sunrise"
  entity_sunset: "input_number.nursery_sunset"
  entity_enable: "input_boolean.nursery_enabled"

packages:
  core: !include common/core.yaml
  switchbot: !include common/switchbot.yaml
  crypto: !include common/crypto.yaml
  wifi: !include common/wifi-public.yaml
  portal: !include common/portal.yaml
  bluetooth: !include common/bluetooth.yaml
  #pawscout: !include common/pawscout.yaml # too close to SB1
  schedule: !include common/light_schedule.yaml

