substitutions:
  devicename: "esp-talk-d1"
  board: wemos_d1_mini32
  reboot_timeout: 2min

  ota_password: !secret talk_d1_ota
  api_key: !secret talk_d1_key

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  speaker: !include common/speaker.yaml
  wifi: !include common/wifi-public.yaml
  portal: !include common/portal.yaml
