# Office
substitutions:
  devicename: "esp-talk-d2"
  board: wemos_d1_mini32
  reboot_timeout: 2min
  ota_password: !secret talk_d2_ota
  api_key: !secret talk_d2_key
  fast_connect: "true"

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  speaker: !include common/speaker.yaml
  wifi: !include common/wifi-public.yaml
  portal: !include common/portal.yaml

