substitutions:
  devicename: "esp-catfood"
  # ESP32
  board: esp32cam

  # Core
  ota_password: !secret catfood_ota
  api_key: !secret catfood_key

  # Camera
  vertical_flip: "false"
  horizontal_mirror: "false"
  fps: "10 fps"
  resolution: 1024x768
  jpeg_quality: "20"
  agc_gain_ceiling: 128x
  aec2: "true"
  ae_level: "1"
  brightness: "2"
  saturation: "2"

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  camera: !include common/espcam.yaml
  stream: !include common/espcam-web.yaml
  snap: !include
    file: common/espcam-web.yaml
    vars:
      mode: snapshot
      port: "8081"
  wifi: !include common/wifi-unified-iot.yaml
  portal: !include common/portal.yaml

