substitutions:
  devicename: "esp-cam-test2"

  # ESP32
  board: esp32cam

  # Core
  ota_password: !secret cam_test2_ota
  api_key: !secret cam_test2_key

  # Camera
  fps: "10 fps"
  resolution: 1280x1024
  jpeg_quality: "12"
  agc_gain_ceiling: 128x
  aec2: "true"
  ae_level: "1"
  brightness: "1"
  saturation: "2"
  horizontal_mirror: "false"
  vertical_flip: "false"

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  camera: !include common/espcam.yaml
  wifi: !include common/wifi-iot.yaml
  portal: !include common/portal.yaml
