# Wrover
substitutions:
  devicename: "partyroom-rover"
  # ESP32
  board: esp-wrover-kit
  framework: arduino

  ota_password: !secret partyroom_ota
  api_key: !secret partyroom_key

packages:
  core: !include common/core.yaml
  esp32: !include common/esp32.yaml
  wifi: !include common/wifi-iot.yaml
  pawscout: !include common/pawscout.yaml
  portal: !include common/portal.yaml
