# Wrover
substitutions:
  devicename: "partyroom-rover"
  board: esp-wrover-kit
  #framework: arduino
  framework: esp-idf

  ota_password: !secret partyroom_ota
  api_key: !secret partyroom_key

packages:
  core: !include common/core.yaml
  crypto: !include common/crypto.yaml
  esp32: !include common/esp32.yaml
  wifi: !include common/wifi-unified-iot.yaml
  bluetooth: !include common/bluetooth.yaml
  pawscout: !include common/pawscout.yaml
  portal: !include common/portal.yaml

