substitutions:
  devicename: "plantdog"
  board: esp-wrover-kit
  framework: esp-idf

  ota_password: !secret plantdog_ota
  api_key: !secret plantdog_key

packages:
  core: !include common/core.yaml
  esp32: !include common/esp32.yaml
  crypto: !include common/crypto.yaml
  wifi: !include common/wifi-unified-iot.yaml
  portal: !include common/portal.yaml
  bluetooth: !include common/bluetooth.yaml
  pawscout: !include common/pawscout.yaml

