substitutions:
  devicename: "Unknown omg who am I even?"
  pawscout_uuid_0: !secret pawscout_uuid_0
  pawscout_uuid_1: !secret pawscout_uuid_1

  petname: !secret petname

esphome:
  includes:
    # https://github.com/rpatel3001/BleDistance/
    - custom_components/lib/OneEuro.h
    - custom_components/ble_dist.h
  on_boot:
    then:
      lambda: |-
        addTracker("PawScout-0", "$pawscout_uuid_0");
        addTracker("PawScout-1", "$pawscout_uuid_1");

logger:
  logs:
    esp32_ble_tracker: INFO

# https://esphome.io/components/esp32_ble_tracker.html
esp32_ble_tracker:
  scan_parameters:
    active: true
  on_ble_advertise:
    then:
      - lambda: |-
          parseAdvertisement(x);

sensor:
  - platform: template
    name: "${petname}-Pawscout-Distance-${devicename}"
    id: pawscout_dist
    update_interval: 30s
    unit_of_measurement: "ft"
    device_class: ""
    state_class: "measurement"
    accuracy_decimals: 1
    #entity_category: "diagnostic"
    icon: "mdi:signal-distance-variant"
    lambda: |-
      return std::min(getTracker("PawScout-0").get_dist(), getTracker("PawScout-1").get_dist());

