substitutions:
  devicename: "Unknown omg who am I even?"
  pawscout_uuid_0: !secret pawscout_uuid_0
  pawscout_uuid_1: !secret pawscout_uuid_1

  petname: !secret petname

esphome:
  includes:
    # https://github.com/rpatel3001/BleDistance/
    - custom_components/lib/OneEuro.h
    - custom_components/ble_dist.h
  on_boot:
    then:
      lambda: |-
        addTracker("PawScout-0", "$pawscout_uuid_0");
        addTracker("PawScout-1", "$pawscout_uuid_1");

logger:
  logs:
    esp32_ble_tracker: INFO

api:
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

# https://esphome.io/components/esp32_ble_tracker.html
esp32_ble_tracker:
  scan_parameters:
    active: true
    continuous: false
  on_ble_advertise:
    then:
      - lambda: |-
          parseAdvertisement(x);

sensor:
  - platform: template
    name: "${petname}-Pawscout-Distance-${devicename}"
    id: pawscout_dist
    update_interval: 15s
    unit_of_measurement: "ft"
    device_class: ""
    state_class: "measurement"
    accuracy_decimals: 1
    #entity_category: "diagnostic"
    icon: "mdi:signal-distance-variant"
    # Unrolled some logic but NAN is basically "not comparable" to numbers.
    lambda: |-
      float dist0 = getTracker("PawScout-0").get_dist();
      float dist1 = getTracker("PawScout-1").get_dist();
      if (isnan(dist0)) {
        ESP_LOGD("ble_dist","Returning PS1: %f", dist1 );
        return dist1;
      }
      if (isnan(dist1)) {
        ESP_LOGD("ble_dist","Returning PS0: %f", dist0);
        return dist0;
      }
      float dist = std::min(dist0, dist1);
      ESP_LOGD("ble_dist","Returning MIN: %f", dist);
      return dist;
