# Parameters:
substitutions:
  reboot_timeout: 1min
  fast_connect: "false"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  reboot_timeout: ${reboot_timeout}
  fast_connect: ${fast_connect}
