# Fix this to be one file using nesting or something
# Parameters:
substitutions:
  reboot_timeout: 1min
  fast_connect: "false"

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

  reboot_timeout: "${reboot_timeout}"
  fast_connect: "${fast_connect}"
