# Parameters:
substitutions:
  reboot_timeout: 1min
  fast_connect: "false"
  # None, light, high
  power_save_mode: "light"

wifi:
  ssid: !secret wifi_unified_ssid
  password: !secret wifi_unified_pub_password

  reboot_timeout: "${reboot_timeout}"
  fast_connect: "${fast_connect}"
  power_save_mode: "${power_save_mode}"

